tours/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
    url(r'^addtour/$', views.add_tour, name='add_tour'),
    url(r'^showstops/([0-9]+)$', views.show_stops, name='show_stops'),
    url(r'^edittour/([0-9]+)$', views.edit_tour, name='edit_tour'),
    url(r'^deletetour/([0-9]+)$', views.delete_tour, name='delete_tour'),
    url(r'^deletestop/([0-9]+)$', views.delete_stop, name='delete_stop'),
]

travel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^guides/', include('guides.urls', namespace='manage_guides')),
    url(r'^tours/', include('tours.urls', namespace='manage_tours')),
    url(r'^suppliers/', include('suppliers.urls', namespace='manage_suppliers')),
    url(r'^registrations/', include('registrations.urls', namespace='registrations')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tours/models.py
from django.db import models
from guides.models import City

# Create your models here.


class Kind(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Tour(models.Model):
    title = models.CharField(max_length=50)
    city = models.ForeignKey(City, related_name="tourtocities")
    kind = models.ForeignKey(Kind, related_name="tourtokinds")
    description = models.CharField(max_length=100, blank=True)
    duration = models.DurationField()
    minGroup = models.SmallIntegerField()
    maxGroup = models.SmallIntegerField()
    pricePerson = models.SmallIntegerField()
    priceChild = models.SmallIntegerField()

    def __str__(self):
        return self.title


class Suplier(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Stop(models.Model):
    name = models.CharField(max_length=30)
    startTime = models.DateTimeField()
    duration = models.DurationField()
    description = models.CharField(max_length=100, blank=True)
    tour = models.ForeignKey(Tour)
    suplier = models.ManyToManyField(Suplier)

    def __str__(self):
        return self.name

tours/forms.py
from django import forms
from .models import Tour, Stop


class TourForm(forms.ModelForm):
    class Meta:
        model = Tour
        fields = [
            'title', 'city', 'kind', 'description', 'duration',
            'minGroup', 'maxGroup', 'pricePerson', 'priceChild'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
            'kind': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'duration': forms.TextInput(attrs={'class': 'form-control'}),
            'minGroup': forms.NumberInput(attrs={'class': 'form-control'}),
            'maxGroup': forms.NumberInput(attrs={'class': 'form-control'}),
            'pricePerson': forms.NumberInput(attrs={'class': 'form-control'}),
            'priceChild': forms.NumberInput(attrs={'class': 'form-control'})
        }
        labels = {
            'title': 'Title',
            'city': 'City',
            'kind': 'Type',
            'description': 'Description',
            'duration': 'Duration',
            'minGroup': 'Min group',
            'maxGroup': 'Max group',
            'pricePerson': 'Per person',
            'priceChild': 'Per child'
        }


class StopForm(forms.ModelForm):
    class Meta:
        model = Stop
        fields = ['name', 'startTime', 'duration', 'description', 'suplier']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'startTime': forms.TextInput(attrs={'class': 'form-control'}),
            'duration': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'suplier': forms.SelectMultiple(attrs={'id':'custom-headers', 'multiple': 'multiple'})
        }

tours/views.py
from .forms import StopForm
from .forms import TourForm
from .models import Stop
from .models import Tour
from django.core.urlresolvers import reverse
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from utils.views import render_to
# Create your views here.


@render_to('tours.html')
def overview(request):
    if 'id_city' in request.session:
        tours = Tour.objects.filter(city=request.session['id_city'])
    else:
        tours = Tour.objects.all()

    if request.method == 'POST':
        query = request.POST.get("search")

        if query:
            tours = tours.filter(title__contains=query)

    return {'Tours': tours}


@render_to('show-stops.html')
def show_stops(request, id):
    tour = get_object_or_404(Tour, pk=id)
    stopFormSet = inlineformset_factory(Tour, Stop, extra=0, form=StopForm)
    stop_formset = stopFormSet(instance=tour)
    return {'stopformset': stop_formset}


@render_to('add-tour.html')
def add_tour(request):
    stopFormSet = inlineformset_factory(Tour, Stop, extra=1, form=StopForm)

    if request.method == 'POST':
        tour_form = TourForm(request.POST)
        stop_formset = stopFormSet(request.POST)
        if tour_form.is_valid() and stop_formset.is_valid():
            instance = tour_form.save()
            stop_formset.instance = instance
            stop_formset.save()
            return HttpResponseRedirect(reverse('manage_tours:overview'))
    else:
        stop_formset = stopFormSet(queryset=Stop.objects.none())
        tour_form = TourForm()
        # import ipdb; ipdb.set_trace()
    return {'tourform': tour_form, 'stopformset': stop_formset}


def delete_tour(request, id):
    instance = get_object_or_404(Tour, pk=id)
    Stop.objects.filter(tour=instance).delete()
    Tour.objects.get(pk=id).delete()
    return HttpResponseRedirect(reverse('manage_tours:overview'))


def delete_stop(request, id):
    Stop.objects.get(pk=id).delete()
    return HttpResponseRedirect(reverse('manage_tours:overview'))


@render_to('edit-tour.html')
def edit_tour(request, id):
    tour = get_object_or_404(Tour, pk=id)
    tour_form = TourForm(instance=tour)
    stopFormSet = inlineformset_factory(Tour, Stop, extra=0, form=StopForm)
    stop_formset = stopFormSet(instance=tour)

    if request.method == 'POST':
        tour_form = TourForm(request.POST, instance=tour)
        tour = tour_form.save(commit=False)
        stop_formset = stopFormSet(request.POST, instance=tour)
        if tour_form.is_valid() and stop_formset.is_valid():
            tour_form.save()
            stop_formset.save()
            return HttpResponseRedirect(reverse('manage_tours:overview'))

    return {'tourform': tour_form, 'stopformset': stop_formset}

templates/tours/add-tour.html
 <!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <link href="{% static "css/multi-select.css" %}" media="screen" rel="stylesheet" type="text/css">
    <script src="{% static "js/jquery.multi-select.js" %}"></script>
    <script src="{% static "js/jquery.quicksearch.js" %}"></script>

<div id="empty_form" style="display:none">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="col-md-10">Contact person</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content">
        <div class="row">
          <div class="col-md-6 form-group">
              {{ stopformset.empty_form.name.label_tag }}
              {{ stopformset.empty_form.name.errors }}
              {{ stopformset.empty_form.name }}

              {{ stopformset.empty_form.startTime.label_tag }}
              {{ stopformset.empty_form.startTime.errors }}
              {{ stopformset.empty_form.startTime }}

              {{ stopformset.empty_form.duration.label_tag }}
              {{ stopformset.empty_form.duration.errors }}
              {{ stopformset.empty_form.duration }}

              {{ stopformset.empty_form.description.label_tag }}
              {{ stopformset.empty_form.description.errors }}
              {{ stopformset.empty_form.description }}
          </div>
          <div class="col-md-6 form-group">
            {{ stopformset.empty_form.suplier.label_tag }}
            {{ stopformset.empty_form.suplier.errors }}
            {{ stopformset.empty_form.suplier }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<form action="" method="POST" id="addguide">
{% csrf_token %}
  <h1>Add tour</h1>
  <div class="panel panel-group">
    <div class="tab-content">
      <div class="row">
        <div class="col-md-6">
          <!--GENERAL PANEL-->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="col-md-6">General information</h2>
            </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-12 form-group">
                      {{ tourform.title.label_tag }}
                      {{ tourform.title.errors }}
                      {{ tourform.title }}
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 form-group">
                    {{ tourform.city.label_tag }}
                    {{ tourform.city.errors }}
                    {{ tourform.city }}
                  </div>
                  <div class="col-md-6 form-group">
                    {{ tourform.kind.label_tag }}
                    {{ tourform.kind.errors }}
                    {{ tourform.kind }}
                  </div>
                </div>
                <div class="row">
                    <div class="col-md-12 form-group">
                      {{ tourform.description.label_tag }}
                      {{ tourform.description.errors }}
                      {{ tourform.description }}
                    </div>
                </div>
              </div>
            </div>
          </div>
          <!--ENDGENERAL PANEL-->
        </div>
        <div class="col-md-6">
          <!--EXTRA PANEL-->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="col-md-6">Extra information</h2>
            </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-4 form-group">
                      {{ tourform.duration.label_tag }}
                      {{ tourform.duration.errors }}
                      {{ tourform.duration }}
                  </div>
                  <div class="col-md-4 form-group">
                      {{ tourform.minGroup.label_tag }}
                      {{ tourform.minGroup.errors }}
                      {{ tourform.minGroup }}
                  </div>
                  <div class="col-md-4 form-group">
                      {{ tourform.maxGroup.label_tag }}
                      {{ tourform.maxGroup.errors }}
                      {{ tourform.maxGroup }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--ENDEXTRA PANEL-->
          <!--PRICE PANEL-->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="col-md-6">Price information</h2>
            </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-6 form-group">
                      {{ tourform.pricePerson.label_tag }}
                      {{ tourform.pricePerson.errors }}
                      {{ tourform.pricePerson }}
                  </div>
                  <div class="col-md-6 form-group">
                      {{ tourform.priceChild.label_tag }}
                      {{ tourform.priceChild.errors }}
                      {{ tourform.priceChild }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--ENDPRICE PANEL-->
        </div>
      </div>
    </div>
    </div>
  <!--ADD PANEL-->
  {{ stopformset.management_form }}
  <div id="form_set">
  {% for stopform in stopformset %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="col-md-10">Add stop</h2>
      </div>
      <div class="panel-body no-padding-bottom">
        <div class="tab-content">
          <div class="row">
            <div class="col-md-6 form-group">
              {{ stopform.name.label_tag }}
              {{ stopform.name.errors }}
              {{ stopform.name }}

              {{ stopform.startTime.label_tag }}
              {{ stopform.startTime.errors }}
              {{ stopform.startTime }}

              {{ stopform.duration.label_tag }}
              {{ stopform.duration.errors }}
              {{ stopform.duration }}

              {{ stopform.description.label_tag }}
              {{ stopform.description.errors }}
              {{ stopform.description }}
            </div>
            <div class="col-md-6 form-group">
              <select id='custom-headers' multiple='multiple'>
                <option value='elem_1' selected>elem 1</option>
                <option value='elem_2'>elem 2</option>
                <option value='elem_3'>elem 3</option>
                <option value='elem_4' selected>elem 4</option>
                <option value='elem_100'>elem 100</option>
              </select>

            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  </div>
      <input type="button" class="btn btn-primary" value="add more stop" id="add_more">
      <input type="button" class="btn btn-danger" value="delete last stop" id="delete">
  <script>


      $("#add_more").click(function() {
          var form_idx = $('#id_stop_set-TOTAL_FORMS').val();
          $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
          $('#id_stop_set-TOTAL_FORMS').val(parseInt(form_idx) + 1);
      });

      $("#delete").click(function() {
        var form_idx = $('#id_stop_set-TOTAL_FORMS').val();
        if ($('#id_stop_set-TOTAL_FORMS').val() > 1 && $('.panel.panel-default:last').id !== 'empty_form')
        {
            $('.panel.panel-default:last').remove();
            $('#id_stop_set-TOTAL_FORMS').val(parseInt(form_idx) - 1);
        }
      });

      $('#custom-headers').multiSelect({
        selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='try \"12\"'>",
        selectionHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='try \"4\"'>",
        afterInit: function(ms){
          var that = this,
              $selectableSearch = that.$selectableUl.prev(),
              $selectionSearch = that.$selectionUl.prev(),
              selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
              selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

          that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
          .on('keydown', function(e){
            if (e.which === 40){
              that.$selectableUl.focus();
              return false;
            }
          });

          that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
          .on('keydown', function(e){
            if (e.which == 40){
              that.$selectionUl.focus();
              return false;
            }
          });
        },
        afterSelect: function(){
          this.qs1.cache();
          this.qs2.cache();
        },
        afterDeselect: function(){
          this.qs1.cache();
          this.qs2.cache();
        }
      });

  </script>

  <!--ENDL PANEL-->
</form>


<button type="submit" class="btn btn-success" form="addguide" style="float:right">Add tour</button>

{% endblock %}

templates/tours/edit-tour.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div id="empty_form" style="display:none">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="col-md-10">Add stop</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content">
        <div class="row">
          <div class="col-md-6 form-group">
            {{ stopformset.empty_form.name.label_tag }}
            {{ stopformset.empty_form.name.errors }}
            {{ stopformset.empty_form.name }}

            {{ stopformset.empty_form.startTime.label_tag }}
            {{ stopformset.empty_form.startTime.errors }}
            {{ stopformset.empty_form.startTime }}

            {{ stopformset.empty_form.duration.label_tag }}
            {{ stopformset.empty_form.duration.errors }}
            {{ stopformset.empty_form.duration }}

            {{ stopformset.empty_form.description.label_tag }}
            {{ stopformset.empty_form.description.errors }}
            {{ stopformset.empty_form.description }}
          </div>
          <div class="col-md-6 form-group">
            
            {{ stopformset.empty_form.suplier.label_tag }}
            {{ stopformset.empty_form.suplier.errors }}
            {{ stopformset.empty_form.suplier }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<form action="" method="POST" id="edittour">
    {% csrf_token %}
  <h1>Edit tour</h1>
  <div class="panel panel-group">
    <div class="tab-content">
      <div class="row">
        <div class="col-md-6">
          <!--GENERAL PANEL-->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="col-md-6">General information</h2>
            </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-12 form-group">
                      {{ tourform.title.label_tag }}
                      {{ tourform.title.errors }}
                      {{ tourform.title }}
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 form-group">
                    {{ tourform.city.label_tag }}
                    {{ tourform.city.errors }}
                    {{ tourform.city }}
                  </div>
                  <div class="col-md-6 form-group">
                    {{ tourform.kind.label_tag }}
                    {{ tourform.kind.errors }}
                    {{ tourform.kind }}
                  </div>
                </div>
                <div class="row">
                    <div class="col-md-12 form-group">
                      {{ tourform.description.label_tag }}
                      {{ tourform.description.errors }}
                      {{ tourform.description }}
                    </div>
                </div>
              </div>
            </div>
          </div>
          <!--ENDGENERAL PANEL-->
        </div>
        <div class="col-md-6">
          <!--EXTRA PANEL-->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="col-md-6">Extra information</h2>
            </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-4 form-group">
                      {{ tourform.duration.label_tag }}
                      {{ tourform.duration.errors }}
                      {{ tourform.duration }}
                  </div>
                  <div class="col-md-4 form-group">
                      {{ tourform.minGroup.label_tag }}
                      {{ tourform.minGroup.errors }}
                      {{ tourform.minGroup }}
                  </div>
                  <div class="col-md-4 form-group">
                      {{ tourform.maxGroup.label_tag }}
                      {{ tourform.maxGroup.errors }}
                      {{ tourform.maxGroup }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--ENDEXTRA PANEL-->
          <!--PRICE PANEL-->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="col-md-6">Price information</h2>
            </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-6 form-group">
                      {{ tourform.pricePerson.label_tag }}
                      {{ tourform.pricePerson.errors }}
                      {{ tourform.pricePerson }}
                  </div>
                  <div class="col-md-6 form-group">
                      {{ tourform.priceChild.label_tag }}
                      {{ tourform.priceChild.errors }}
                      {{ tourform.priceChild }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!--ENDPRICE PANEL-->
        </div>
      </div>
    </div>
  </div>
  {{ stopformset.management_form }}
  <div id="form_set">
  {% for stopform in stopformset %}

    <div class="panel panel-default">
      {{ stopform.id }}
      <div class="panel-heading">
        <h2 class="col-md-10">Add stop</h2>
      </div>
      <div class="panel-body no-padding-bottom">
        <div class="tab-content">
          <div class="row">
            <div class="col-md-6 form-group">
              {{ stopform.name.label_tag }}
              {{ stopform.name.errors }}
              {{ stopform.name }}

              {{ stopform.startTime.label_tag }}
              {{ stopform.startTime.errors }}
              {{ stopform.startTime }}

              {{ stopform.duration.label_tag }}
              {{ stopform.duration.errors }}
              {{ stopform.duration }}

              {{ stopform.description.label_tag }}
              {{ stopform.description.errors }}
              {{ stopform.description }}
            </div>
            <div class="col-md-6 form-group">
              {{ stopform.suplier.label_tag }}
              {{ stopform.suplier.errors }}
              {{ stopform.suplier }}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>

    <input type="button" class="btn btn-primary" value="add more stop" id="add_more">
    <input type="button" class="btn btn-danger" value="delete last stop" id="delete">
    <script>
        $("#add_more").click(function() {
            var form_idx = $('#id_stop_set-TOTAL_FORMS').val();
            $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
            $('#id_stop_set-TOTAL_FORMS').val(parseInt(form_idx) + 1);
        });

        $("#delete").click(function() {
          var form_idx = $('#id_stop_set-TOTAL_FORMS').val();
          if ($('#id_stop_set-TOTAL_FORMS').val() > 1 && $('.panel.panel-default:last').id !== 'empty_form')
          {
              $('.panel.panel-default:last').remove();
              $('#id_stop_set-TOTAL_FORMS').val(parseInt(form_idx) - 1);
          }
        });
    </script>

<!--ENDL PANEL-->
</form>

<button type="submit" class="btn btn-success" form="edittour" style="float:right">Update tour</button>
{% endblock %}

templates/tours/show-stops.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

{{ stopformset.management_form }}
<div id="form_set">
{% for stopform in stopformset %}

  <div class="panel panel-default">
    <div class="panel-heading">
      {% url 'manage_tours:delete_stop' stopform.id.value as delete %}
      <a href="{{delete}}"><input type="button" class="btn btn-danger" value="Delete stop"></a>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content">
        <div class="row">
          <div class="col-md-3 form-group">
            {{ stopform.name.label_tag }}
            {{ stopform.name.errors }}
            {{ stopform.name }}
          </div>
          <div class="col-md-6 form-group">
            {{ stopform.suplier.label_tag }}
            {{ stopform.suplier.errors }}
            {{ stopform.suplier }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 form-group">
            {{ stopform.startTime.label_tag }}
            {{ stopform.startTime.errors }}
            {{ stopform.startTime }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 form-group">
            {{ stopform.duration.label_tag }}
            {{ stopform.duration.errors }}
            {{ stopform.duration }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-9 form-group">
            {{ stopform.description.label_tag }}
            {{ stopform.description.errors }}
            {{ stopform.description }}
          </div>
        </div>
      </div>

    </div>
  </div>

{% endfor %}
</div>

{% endblock %}

templates/tours/tours.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}

<div class="row">
  <div class="col-xs-6 col-md-4">
    <h1>Tours</h1>
  </div>
  <div class="col-xs-6 col-md-5" style="margin-top: 20px">
    <form id="formsearch" action="" method="post">
      {% csrf_token %}
      <input name="search" type="text" class="form-control" placeholder="Search...">
    </form>
  </div>
  <div class="col-xs-6 col-md-3" style="margin-top: 20px">
    <button type="submit" form="formsearch" class="btn btn-default"><i class="fa fa-search"></i></button>
  </div>
</div>

<table class="table table-condensed">

  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Type</th>
    <th>Duration</th>
    <th>Stops</th>
    <th>
      {% url 'manage_tours:add_tour' as add %}
      <a href="{{ add }}"><button class="btn btn-success"><i class="fa fa-plus"></i></button></a>
    </th>
  </tr>
  {% for tour in Tours %}
  <tr>
      <td>{{ tour.title }}</td>
      <td>{{ tour.city }}</td>
      <td>{{ tour.kind }} </td>
      <td>{{ tour.duration }}</td>
      {% url 'manage_tours:show_stops' tour.id as show %}
      <td><a href="{{ show }}"><button class="btn btn-info"><i class="fa fa-eye"></i></button></a></td>
      <td>
        {% url 'manage_tours:edit_tour' tour.id as edit %}
        {% url 'manage_tours:delete_tour' tour.id as delete %}
          <a href="{{ edit }}">
            <button class="btn btn-primary">
              <i class="fa fa-pencil-square-o"></i>
            </button>
          </a>
          <a href="{{ delete }}">
            <button class="btn btn-danger">
              <i class="fa fa-trash-o"></i>
            </button>
          </a>
      </td>
  </tr>
  {% endfor %}
</table>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

{% endblock %}