suppliers/urls.py
from . import views
from django.conf.urls import url


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
    url(r'^addsupplier/$', views.add_supplier, name='add_supplier'),
    url(r'^editsupplier/([0-9]+)$', views.edit_supplier, name='edit_supplier'),
    url(r'^gettoursedit/$', views.get_tours_edit, name='get_tours_edit'),
    url(r'^gettoursadd/$', views.get_tours_add, name='get_tour_sadd'),
    url(r'^delete/([0-9]+)$', views.delete_supplier, name='delete_supplier')
]

tours/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
    url(r'^addtour/$', views.add_tour, name='add_tour'),
    url(r'^showstops/([0-9]+)$', views.show_stops, name='show_stops'),
    url(r'^edittour/([0-9]+)$', views.edit_tour, name='edit_tour'),
    url(r'^deletetour/([0-9]+)$', views.delete_tour, name='delete_tour'),
    url(r'^deletestop/([0-9]+)$', views.delete_stop, name='delete_stop'),
]

travel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^guides/', include('guides.urls', namespace='manage_guides')),
    url(r'^tours/', include('tours.urls', namespace='manage_tours')),
    url(r'^suppliers/', include('suppliers.urls', namespace='manage_suppliers')),
    url(r'^registrations/', include('registrations.urls', namespace='registrations')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

suppliers/models.py
from django.db import models
from guides.models import City
from guides.models import Country
from tours.models import Tour


class Kind(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Supplier(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=30)
    country = models.ForeignKey(Country)
    city = models.ForeignKey(City)
    kind = models.ForeignKey(Kind)
    postCode = models.IntegerField()
    tour = models.ManyToManyField(Tour)
    email = models.EmailField()
    phoneNumber = models.CharField(max_length=13)
    minGroup = models.SmallIntegerField()
    maxGroup = models.SmallIntegerField()

    def __str__(self):
        return self.name


class ContactPerson(models.Model):
    firstName = models.CharField(max_length=20)
    lastName = models.CharField(max_length=25)
    email = models.EmailField()
    phoneNumber = models.CharField(max_length=13)
    supplier = models.ForeignKey(Supplier)

    def __str__(self):
        return self.firstName + " " + self.lastName

suppliers/forms.py
from django import forms
from .models import Supplier, ContactPerson


class SupplierForm(forms.ModelForm):

    class Meta:
        model = Supplier
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.Select(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
            'kind': forms.Select(attrs={'class': 'form-control'}),
            'postCode': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'tour': forms.CheckboxSelectMultiple(),
            'phoneNumber': forms.TextInput(attrs={'class': 'form-control'}),
            'minGroup': forms.NumberInput(attrs={'class': 'form-control'}),
            'maxGroup': forms.NumberInput(attrs={'class': 'form-control'})
        }
        labels = {
            'name': 'Company',
            'address': 'Address',
            'country': 'Country',
            'city': 'City',
            'kind': 'Type',
            'postCode': 'Post code',
            'tour': 'Tour',
            'email': 'Email',
            'phoneNumber': 'Phone number',
            'minGroup': 'Min group',
            'maxGroup': 'Max group'
        }


class ContactPersonForm(forms.ModelForm):

    class Meta:
        model = ContactPerson
        fields = '__all__'
        widgets = {
            'firstName': forms.TextInput(attrs={'class': 'form-control'}),
            'lastName': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'phoneNumber': forms.TextInput(attrs={'class': 'form-control'}),
            'supplier': forms.Select(attrs={'class': 'form-control'})
        }
        labels = {
            'firstName': 'First name',
            'lastName': 'Last name',
            'email': 'Email',
            'phoneNumber': 'Phone number',
            'supplier': 'Supplier'
        }

suppliers/views.py
from .forms import ContactPersonForm
from .forms import SupplierForm
from .models import ContactPerson
from .models import Supplier
from django.core.urlresolvers import reverse
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from tours.models import Tour
from utils.views import render_json
from utils.views import render_to


@render_to('suppliers.html')
def overview(request):
    if 'id_city' in request.session:
        supplers = Supplier.objects.filter(city=request.session['id_city'])
        return {'Suppliers': supplers}
    else:
        supplers = Supplier.objects.all()
        return {'Suppliers': supplers}


@render_to('add-supplier.html')
def add_supplier(request):

    contactFormSet = inlineformset_factory(
        Supplier, ContactPerson, extra=1, form=ContactPersonForm)
    if request.method == 'POST':
        # import ipdb; ipdb.set_trace()
        supplier_form = SupplierForm(request.POST)
        contact_formset = contactFormSet(request.POST)
        if supplier_form.is_valid() and contact_formset.is_valid():

            instance = supplier_form.save()
            contact_formset.instance = instance
            contact_formset.save()

            return HttpResponseRedirect(reverse('manage_suppliers:overview'))

    else:
        supplier_form = SupplierForm()
        contact_formset = contactFormSet(queryset=ContactPerson.objects.none())
    return {
        'supplierform': supplier_form,
        'contactformset': contact_formset
    }


@render_json
def get_tours_add(request):
    if request.is_ajax() and request.method == 'GET':
        tours = Tour.objects.filter(city=request.GET.get('city_id'))
        if tours:
            tours_data = [(tour.id, tour.title) for tour in tours]
            return {
                'success': True,
                'data': {'tours': tours_data}
            }

    return {'success': False}


@render_json
def get_tours_edit(request):
    if request.is_ajax() and request.method == 'GET':
        tours = Tour.objects.filter(city=request.GET.get('city_id'))
        supplier = Supplier.objects.get(pk=request.GET.get('supplier_id'))

        if tours:
            tours_data = [(tour.id, tour.title, True) if tour in supplier.tour.all() else (tour.id, tour.title, False) for tour in tours]
            return {
                'success': True,
                'data': {'tours': tours_data}
            }

    return {'success': False}


@render_to('edit-supplier.html')
def edit_supplier(request, id):
    supplier = get_object_or_404(Supplier, pk=id)
    supplier_form = SupplierForm(instance=supplier)
    tours = Tour.objects.filter(city=supplier.city)
    supplier_form.fields['tour'].queryset = tours
    contactFormSet = inlineformset_factory(
        Supplier, ContactPerson, extra=0, form=ContactPersonForm)
    contact_formset = contactFormSet(instance=supplier)
    if request.method == 'POST':

        supplier_form = SupplierForm(request.POST, instance=supplier)
        if supplier_form.is_valid():
            supplier_instance = supplier_form.save(commit=False)
            contact_formset = contactFormSet(request.POST, instance=supplier_instance)
            if contact_formset.is_valid():
                supplier_form.save()
                contact_formset.save()
                return HttpResponseRedirect(reverse('manage_suppliers:overview'))
    return {
        'supplierform': supplier_form,
        'contactformset': contact_formset,
        'supplier_id': id
    }


def delete_supplier(request, id):
    instance = get_object_or_404(Supplier, pk=id)
    ContactPerson.objects.filter(supplier=instance).delete()
    Supplier.objects.filter(pk=id).delete()
    return HttpResponseRedirect(reverse('manage_suppliers:overview'))

templates/suppliers/add-supplier.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}

<div id="empty_form" style="display:none">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="col-md-10">Contact person</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content">
        <div class="row">
          <div class="col-md-4 form-group">
            {{ contactformset.empty_form.firstName.label_tag }}
            {{ contactformset.empty_form.firstName.errors }}
            {{ contactformset.empty_form.firstName }}
          </div>
          <div class="col-md-4 form-group">
            {{ contactformset.empty_form.email.label_tag }}
            {{ contactformset.empty_form.email.errors }}
            {{ contactformset.empty_form.email }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 form-group">
            {{ contactformset.empty_form.lastName.label_tag }}
            {{ contactformset.empty_form.lastName.errors }}
            {{ contactformset.empty_form.lastName }}
          </div>
          <div class="col-md-4 form-group">
            {{ contactformset.empty_form.phoneNumber.label_tag }}
            {{ contactformset.empty_form.phoneNumber.errors }}
            {{ contactformset.empty_form.phoneNumber }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<form action="" method="POST" id="addsupplier">
  {% csrf_token %}
  <h1>Add supplier</h1>
  <!-- GENERAL PANEL -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="col-md-10">General information</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content">
        <div class="row">
            <div class="col-md-4 form-group">
              {{ supplierform.name.label_tag }}
              {{ supplierform.name.errors }}
              {{ supplierform.name }}
            </div>
            <div class="col-md-4 form-group">
              {{ supplierform.address.label_tag }}
              {{ supplierform.address.errors }}
              {{ supplierform.address }}
            </div>
            <div class="col-md-4 form-group">
              {{ supplierform.country.label_tag }}
              {{ supplierform.country.errors }}
              {{ supplierform.country }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 form-group">
              {{ supplierform.kind.label_tag }}
              {{ supplierform.kind.errors }}
              {{ supplierform.kind }}
            </div>
            <div class="col-md-4 form-group">
              {{ supplierform.postCode.label_tag }}
              {{ supplierform.postCode.errors }}
              {{ supplierform.postCode }}
            </div>
            <div class="col-md-4 form-group">
              {{ supplierform.city.label_tag }}
              {{ supplierform.city.errors }}
              {{ supplierform.city }}
            </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ENDGENERAL PANEL -->
  <!-- TOURS PANEL -->
  <div class="panel panel-default" id="tours_panel" style="display:none">
  <div class="panel-heading">
    <h2 class="col-md-10">Tours</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content" id="tours">

      </div>
    </div>
  </div>
  <!-- ENDTOURS PANEL -->
  <div class="panel panel-group">
    <div class="tab-content">
      <div class="row">
        <!-- CONTACTINFO PANEL -->
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
            <h2 class="col-md-10">Contact information</h2>
          </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-6 form-group">
                    {{ supplierform.email.label_tag }}
                    {{ supplierform.email.errors }}
                    {{ supplierform.email }}
                  </div>
                  <div class="col-md-6 form-group">
                    {{ supplierform.phoneNumber.label_tag }}
                    {{ supplierform.phoneNumber.errors }}
                    {{ supplierform.phoneNumber }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- ENDCONTACTINFO PANEL -->
        <!-- EXTRA PANEL -->
        <div class="col-md-6">
          <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="col-md-10">Extra inforamtion</h2>
            </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-6 form-group">
                    {{ supplierform.minGroup.label_tag }}
                    {{ supplierform.minGroup.errors }}
                    {{ supplierform.minGroup }}
                  </div>
                  <div class="col-md-6 form-group">
                    {{ supplierform.maxGroup.label_tag }}
                    {{ supplierform.maxGroup.errors }}
                    {{ supplierform.maxGroup }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        <!-- ENDEXTRA PANEL -->
    </div>
  </div>

  <!-- CONTACTPERSON PANEL -->
  {{ contactformset.management_form }}
  <div id="form_set">
  {% for contactform in contactformset %}
  <div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="col-md-10">Contact person</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content">
        <div class="row">
          <div class="col-md-4 form-group">
            {{ contactform.firstName.label_tag }}
            {{ contactform.firstName.errors }}
            {{ contactform.firstName }}
          </div>
          <div class="col-md-4 form-group">
            {{ contactform.email.label_tag }}
            {{ contactform.email.errors }}
            {{ contactform.email }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 form-group">
            {{ contactform.lastName.label_tag }}
            {{ contactform.lastName.errors }}
            {{ contactform.lastName }}
          </div>
          <div class="col-md-4 form-group">
            {{ contactform.phoneNumber.label_tag }}
            {{ contactform.phoneNumber.errors }}
            {{ contactform.phoneNumber }}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
  <!-- ENDCONTACTPERSON PANEL -->
 
  <input type="button" class="btn btn-primary" value="add more stop" id="add_more">
  <input type="button" class="btn btn-danger" value="delete last stop" id="delete">

  <script>
    $("#add_more").click(function() {
        var form_idx = $('#id_contactperson_set-TOTAL_FORMS').val();
        $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
        $('#id_contactperson_set-TOTAL_FORMS').val(parseInt(form_idx) + 1);
    });

    $("#delete").click(function() {
      var form_idx = $('#id_contactperson_set-TOTAL_FORMS').val();
      if ($('#id_contactperson_set-TOTAL_FORMS').val() > 1 && $('.panel.panel-default:last').id !== 'empty_form')
      {
          $('.panel.panel-default:last').remove();
          $('#id_contactperson_set-TOTAL_FORMS').val(parseInt(form_idx) - 1);
      }
    });

    $('#id_city').change(function() {
      $('#tours').empty();
      $.ajax({
          url: "{% url 'manage_suppliers:get_tour_sadd' %}",
          type: "GET",
          data: { city_id: $(this).val() },

          success: function(responce) {
            responce.data.tours.forEach(function(entry) {
              $("#tours").append("<label><input type='checkbox' name='tour' value="+entry[0]+"> "+entry[1]+"</label><br>");
            });
            $('#tours_panel').attr("style", "display:block");
          }
      });
    });
  </script>
</form>

<button type="submit" class="btn btn-success" form="addsupplier" style="float:right" >Add supplier</button>


{% endblock %}

templates/suppliers/edit-supplier.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<div id="empty_form" style="display:none">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="col-md-10">Contact person</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content">
        <div class="row">
          <div class="col-md-4 form-group">
            {{ contactformset.empty_form.firstName.label_tag }}
            {{ contactformset.empty_form.firstName.errors }}
            {{ contactformset.empty_form.firstName }}
          </div>
          <div class="col-md-4 form-group">
            {{ contactformset.empty_form.email.label_tag }}
            {{ contactformset.empty_form.email.errors }}
            {{ contactformset.empty_form.email }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 form-group">
            {{ contactformset.empty_form.lastName.label_tag }}
            {{ contactformset.empty_form.lastName.errors }}
            {{ contactformset.empty_form.lastName }}
          </div>
          <div class="col-md-4 form-group">
            {{ contactformset.empty_form.phoneNumber.label_tag }}
            {{ contactformset.empty_form.phoneNumber.errors }}
            {{ contactformset.empty_form.phoneNumber }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<form action="" method="POST" id="editsupplier">
  {% csrf_token %}
  <h1>Edit supplier</h1>
  <!-- GENERAL PANEL -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="col-md-10">General information</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content">
        <div class="row">
          <div class="col-md-4 form-group">
            {{ supplierform.name.label_tag }}
            {{ supplierform.name.errors }}
            {{ supplierform.name }}
          </div>
          <div class="col-md-4 form-group">
            {{ supplierform.address.label_tag }}
            {{ supplierform.address.errors }}
            {{ supplierform.address }}
          </div>
          <div class="col-md-4 form-group">
            {{ supplierform.country.label_tag }}
            {{ supplierform.country.errors }}
            {{ supplierform.country }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 form-group">
            {{ supplierform.kind.label_tag }}
            {{ supplierform.kind.errors }}
            {{ supplierform.kind }}
          </div>
          <div class="col-md-4 form-group">
            {{ supplierform.postCode.label_tag }}
            {{ supplierform.postCode.errors }}
            {{ supplierform.postCode }}
          </div>
          <div class="col-md-4 form-group">
            {{ supplierform.city.label_tag }}
            {{ supplierform.city.errors }}
            {{ supplierform.city }}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ENDGENERAL PANEL -->
  <!-- TOURS PANEL -->
  <div class="panel panel-default" id="tours_panel">
    <div class="panel-heading">
      <h2 class="col-md-10">Tours</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content" id="tours">
      {% for tour in supplierform.tour %}
        {{ tour }}
        <br>
      {% endfor %}
      </div>
    </div>
  </div>
  <!-- ENDTOURS PANEL -->
  <div class="panel panel-group">
    <div class="tab-content">
      <div class="row">
        <!-- CONTACTINFO PANEL -->
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2 class="col-md-10">Contact information</h2>
            </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-6 form-group">
                    {{ supplierform.email.label_tag }}
                    {{ supplierform.email.errors }}
                    {{ supplierform.email }}
                  </div>
                  <div class="col-md-6 form-group">
                    {{ supplierform.phoneNumber.label_tag }}
                    {{ supplierform.phoneNumber.errors }}
                    {{ supplierform.phoneNumber }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- ENDCONTACTINFO PANEL -->
        <!-- EXTRA PANEL -->
        <div class="col-md-6">
          <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="col-md-10">Extra inforamtion</h2>
            </div>
            <div class="panel-body no-padding-bottom">
              <div class="tab-content">
                <div class="row">
                  <div class="col-md-6 form-group">
                    {{ supplierform.minGroup.label_tag }}
                    {{ supplierform.minGroup.errors }}
                    {{ supplierform.minGroup }}
                  </div>
                  <div class="col-md-6 form-group">
                    {{ supplierform.maxGroup.label_tag }}
                    {{ supplierform.maxGroup.errors }}
                    {{ supplierform.maxGroup }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        <!-- ENDEXTRA PANEL -->
    </div>
  </div>

  <!-- CONTACTPERSON PANEL -->
  {{ contactformset.management_form }}
  <div id="form_set">
  {% for contactform in contactformset %}
  <div class="panel panel-default">
  {{ contactform.id }}
  <div class="panel-heading">
    <h2 class="col-md-10">Contact person</h2>
    </div>
    <div class="panel-body no-padding-bottom">
      <div class="tab-content">
        <div class="row">
          <div class="col-md-4 form-group">
            {{ contactform.firstName.label_tag }}
            {{ contactform.firstName.errors }}
            {{ contactform.firstName }}
          </div>
          <div class="col-md-4 form-group">
            {{ contactform.email.label_tag }}
            {{ contactform.email.errors }}
            {{ contactform.email }}
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 form-group">
            {{ contactform.lastName.label_tag }}
            {{ contactform.lastName.errors }}
            {{ contactform.lastName }}
          </div>
          <div class="col-md-4 form-group">
            {{ contactform.phoneNumber.label_tag }}
            {{ contactform.phoneNumber.errors }}
            {{ contactform.phoneNumber }}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
  <!-- ENDCONTACTPERSON PANEL -->
 
  <input type="button" class="btn btn-primary" value="add more stop" id="add_more">
  <input type="button" class="btn btn-danger" value="delete last stop" id="delete">

  <script>
    $("#add_more").click(function() {
        var form_idx = $('#id_contactperson_set-TOTAL_FORMS').val();
        $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
        $('#id_contactperson_set-TOTAL_FORMS').val(parseInt(form_idx) + 1);
    });

    $("#delete").click(function() {
      var form_idx = $('#id_contactperson_set-TOTAL_FORMS').val();
      if ($('#id_contactperson_set-TOTAL_FORMS').val() > 1 && $('.panel.panel-default:last').id !== 'empty_form')
      {
          $('.panel.panel-default:last').remove();
          $('#id_contactperson_set-TOTAL_FORMS').val(parseInt(form_idx) - 1);
      }
    });

    $('#id_city').change(function() {
      $('#tours').empty();
      $.ajax({
          url: "{% url 'manage_suppliers:get_tours_edit' %}",
          type: "GET",
          data: { city_id: $(this).val(), supplier_id: {{ supplier_id }} },

          success: function(responce) {
            responce.data.tours.forEach(function(entry) {
              if (entry[2])
                $("#tours").append("<label><input type='checkbox' name='tour' value="+entry[0]+" checked> "+entry[1]+"</label><br>");
              else
                $("#tours").append("<label><input type='checkbox' name='tour' value="+entry[0]+"> "+entry[1]+"</label><br>");
            });
          }
      });
    });
  </script>
</form>

<button type="submit" class="btn btn-success" form="editsupplier" style="float:right" >Edit supplier</button>


{% endblock %}

templates/suppliers/suppliers.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<table class="table table-condensed">
  <h1>Suppliers</h1>
  <tr>
    <th>Company</th>
    <th>Address</th>
    <th>Mobile phone</th>
    <th>Post code</th>
    <th>Max group</th>
    <th>City</th>
    <th>
      {% url 'manage_suppliers:add_supplier' as add %}
      <a href="{{add}}"><button class="btn btn-success"><i class="fa fa-plus"></i></button></a>
    </th>
  </tr>
  {% for supplier in Suppliers %}
  <tr>
      <td>{{ supplier.name }}</td>
      <td>{{ supplier.address }}</td>
      <td>{{ supplier.phoneNumber }} </td>
      <td>{{ supplier.postCode }}</td>
      <td>{{ supplier.maxGroup }}</td>
      <td>{{ supplier.city }}</td>
      <td>
        {% url 'manage_suppliers:edit_supplier' supplier.id as edit %}
        {% url 'manage_suppliers:delete_supplier' supplier.id as delete %}
        <a href="{{edit}}"><button class="btn btn-primary"><i class="fa fa-pencil-square-o"></i></button></a>
        <a href="{{delete}}"><button class="btn btn-danger"><i class="fa fa-trash-o"></i></button></a>
      </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}