guides/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
    url(r'^addguide/$', views.add_guide, name='add_guide'),
    url(r'^editguide/([0-9]+)$', views.edit_guide, name='edit_guide'),
    url(r'^deleteguide/([0-9]+)$', views.delete_guide, name='delete_guide'),

]

tours/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
    url(r'^addtour/$', views.add_tour, name='add_tour'),
    url(r'^showstops/([0-9]+)$', views.show_stops, name='show_stops'),
    url(r'^edittour/([0-9]+)$', views.edit_tour, name='edit_tour'),
    url(r'^deletetour/([0-9]+)$', views.delete_tour, name='delete_tour'),
    url(r'^deletestop/([0-9]+)$', views.delete_stop, name='delete_stop'),
]

travel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^guides/', include('guides.urls', namespace='manage_guides')),
    url(r'^tours/', include('tours.urls', namespace='manage_tours')),
    url(r'^suppliers/', include('suppliers.urls', namespace='manage_suppliers')),
    url(r'^registrations/', include('registrations.urls', namespace='registrations')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

guides/models.py
from django.db import models
from registrations.models import Account
# Create your models here.


class Country(models.Model):
    country = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = "Countries"

    def __str__(self):
        return self.country


class City(models.Model):
    city = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = "Cities"

    def __str__(self):
        return self.city


class Language(models.Model):
    LANG = (
        ('EN', "English"),
        ('RU', "Russian")
    )
    language = models.CharField(max_length=2, choices=LANG, default="EN")

    def __str__(self):
        return self.language


class PaymentMethod(models.Model):
    PM = (
        ('Visa', 'Visa'),
        ('MasterCard', 'MasterCard'),
        ('Cash', 'Cash')
    )
    paymentmethod = models.CharField(max_length=10, choices=PM)

    def __str__(self):
        return self.paymentmethod


class Guid(models.Model):
    address = models.CharField(max_length=30, blank=True)
    bankAccount = models.CharField(max_length=30, blank=True)
    country = models.ForeignKey(Country)
    city = models.ForeignKey(City, related_name='citytoguid')
    language = models.ForeignKey(Language)
    paymentMethod = models.ForeignKey(PaymentMethod)
    account = models.OneToOneField(Account, blank=True)
    cities = models.ManyToManyField(City, related_name='citiestoguid', blank=True)

    def __str__(self):
        return self.address

guides/forms.py
from django import forms
from .models import Guid


class GuideForm(forms.ModelForm):
    
    class Meta:
        model = Guid
        fields = [
            'address', 'bankAccount', 'country', 'city', 'language', 'paymentMethod', 'cities'
        ]
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'bankAccount': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.Select(attrs={'class': 'form-control'}),
            'city': forms.Select(attrs={'class': 'form-control'}),
            'language': forms.Select(attrs={'class': 'form-control'}),
            'paymentMethod': forms.Select(attrs={'class': 'form-control'}),
            'cities': forms.CheckboxSelectMultiple()

        }
        labels = {
            'address': 'Address',
            'bankAccount': 'Bank account',
            'country': 'Country',
            'city': 'City',
            'lang': 'Language',
            'paymentmethod': 'Payment method',
            'cities': 'Cities'
        }

guides/views.py
from .forms import GuideForm
from .models import Guid
from .models import City
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from registrations.forms import AccountForm
from registrations.models import Account
from tours.models import Tour
from utils.views import render_to


@render_to('guides.html')
def overview(request):
    if 'id_city' in request.session:
        guides = Guid.objects.filter(city=request.session['id_city'])
        return {'guides': guides}
    else:
        guides = Guid.objects.all()
        return {'guides': guides}


@render_to('add-guide.html')
def add_guide(request):
    id_cities = Tour.objects.values_list('city', flat=True).distinct()
    cities = City.objects.filter(id__in=id_cities)

    if request.method == 'POST':
        guide_form = GuideForm(request.POST)
        account_form = AccountForm(request.POST)
        if guide_form.is_valid() and account_form.is_valid():
            account = account_form.save()
            guide = guide_form.save(commit=False)
            guide.account = account
            guide.save()
            return HttpResponseRedirect(reverse('manage_guides:overview'))
    else:
        # import ipdb; ipdb.set_trace()
        guide_form = GuideForm()
        guide_form['cities'].field.queryset = cities
        account_form = AccountForm()

    return {'guideForm': guide_form, 'accountForm': account_form}


def delete_guide(request, id):
    guide = Guid.objects.get(pk=id)
    Account.objects.get(email=guide.account).delete()
    guide.delete()
    return HttpResponseRedirect(reverse('manage_guides:overview'))


@render_to('edit-guide.html')
def edit_guide(request, id):
    guide = get_object_or_404(Guid, pk=id)
    id_cities = Tour.objects.values_list('city', flat=True).distinct()
    cities = City.objects.filter(id__in=id_cities)

    if request.method == 'POST':
        guide_form = GuideForm(request.POST, instance=guide)
        # guide_form['cities'].field.queryset = cities
        account_form = AccountForm(request.POST, instance=guide.account)
        if guide_form.is_valid() and account_form.is_valid():
            guide_form.save()
            account_form.save()
            return HttpResponseRedirect(reverse('manage_guides:overview'))
    else:
        # import ipdb; ipdb.set_trace()
        guide_form = GuideForm(instance=guide)
        guide_form['cities'].field.queryset = cities
        account_form = AccountForm(instance=guide.account)

    return {'guideForm': guide_form, 'accountForm': account_form}

templates/guides/add-guide.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


<form action="" method="POST" id="addguide">
  {% csrf_token %}
 <h1>Add guide</h1>
  <div class="panel panel-default">

  <div class="panel-heading">
    <h2 class="col-md-10">General information</h2>
  </div>
  <div class="panel-body no-padding-bottom">
    <div class="tab-content">
      <div class="row">
        <div class="col-md-4 form-group">
          {{ accountForm.first_name.label_tag }}
          {{ accountForm.first_name.errors }}
          {{ accountForm.first_name }}
        </div>
        <div class="col-md-4 form-group">
          {{ accountForm.phoneNumber.label_tag }}
          {{ accountForm.phoneNumber.errors }}
          {{ accountForm.phoneNumber }}
        </div>
        <div class="col-md-4 form-group">
          {{ guideForm.country.label_tag }}
          {{ guideForm.country.errors }}
          {{ guideForm.country }}
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 form-group">
          {{ accountForm.last_name.label_tag }}
          {{ accountForm.last_name.errors }}
          {{ accountForm.last_name }}
        </div>
        <div class="col-md-4 form-group">
          {{ accountForm.email.label_tag }}
          {{ accountForm.email.errors }}
          {{ accountForm.email }}
        </div>
        <div class="col-md-4 form-group">
          {{ guideForm.city.label_tag }}
          {{ guideForm.city.errors }}
          {{ guideForm.city }}
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-8 form-group">
          {{ guideForm.address.label_tag }}
          {{ guideForm.address.errors }}
          {{ guideForm.address }}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
  <h2 class="col-md-10">Additional information</h2>
</div>
  <div class="panel-body no-padding-bottom">
    <div class="tab-content">
      <div class="row">
        <div class="col-md-4 form-group">
          {{ guideForm.language.label_tag }}
          {{ guideForm.language.errors }}
          {{ guideForm.language }}
        </div>
        <div class="col-md-4 form-group">
          {{ guideForm.bankAccount.label_tag }}
          {{ guideForm.bankAccount.errors }}
          {{ guideForm.bankAccount }}
        </div>
        <div class="col-md-4 form-group">
          {{ guideForm.paymentMethod.label_tag }}
          {{ guideForm.paymentMethod.errors }}
          {{ guideForm.paymentMethod }}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
<div class="panel-heading">
  <h2 class="col-md-10">Cities</h2>
  </div>
  <div class="panel-body no-padding-bottom">
    <div class="tab-content">
      {{ guideForm.cities }}
    </div>
  </div>
</div>

</form>


<button type="submit" class="btn btn-success" form="addguide" >Add guide</button>
{% endblock %}

templates/guides/edit-guide.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


<form action="" method="POST" id="editguide">
  {% csrf_token %}
 <h1>Edit guide</h1>
  <div class="panel panel-default">

  <div class="panel-heading">
    <h2 class="col-md-10">General information</h2>
  </div>
  <div class="panel-body no-padding-bottom">
    <div class="tab-content">
      <div class="row">
        <div class="col-md-4 form-group">
          {{ accountForm.first_name.label_tag }}
          {{ accountForm.first_name.errors }}
          {{ accountForm.first_name }}
        </div>
        <div class="col-md-4 form-group">
          {{ accountForm.phoneNumber.label_tag }}
          {{ accountForm.phoneNumber.errors }}
          {{ accountForm.phoneNumber }}
        </div>
        <div class="col-md-4 form-group">
          {{ guideForm.country.label_tag }}
          {{ guideForm.country.errors }}
          {{ guideForm.country }}
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 form-group">
          {{ accountForm.last_name.label_tag }}
          {{ accountForm.last_name.errors }}
          {{ accountForm.last_name }}
        </div>
        <div class="col-md-4 form-group">
          {{ accountForm.email.label_tag }}
          {{ accountForm.email.errors }}
          {{ accountForm.email }}
        </div>
        <div class="col-md-4 form-group">
          {{ guideForm.city.label_tag }}
          {{ guideForm.city.errors }}
          {{ guideForm.city }}
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-md-offset-8 form-group">
          {{ guideForm.address.label_tag }}
          {{ guideForm.address.errors }}
          {{ guideForm.address }}
        </div>
      </div>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
  <h2 class="col-md-10">Additional information</h2>
</div>
  <div class="panel-body no-padding-bottom">
    <div class="tab-content">
      <div class="row">
          <div class="col-md-4 form-group">
            {{ guideForm.language.label_tag }}
            {{ guideForm.language.errors }}
            {{ guideForm.language }}
          </div>
          <div class="col-md-4 form-group">
            {{ guideForm.bankAccount.label_tag }}
            {{ guideForm.bankAccount.errors }}
            {{ guideForm.bankAccount }}
          </div>
          <div class="col-md-4 form-group">
            {{ guideForm.paymentMethod.label_tag }}
            {{ guideForm.paymentMethod.errors }}
            {{ guideForm.paymentMethod }}
          </div>
      </div>
    </div>
  </div>
</div>
<div class="panel panel-default">
<div class="panel-heading">
  <h2 class="col-md-10">Cities</h2>
  </div>
  <div class="panel-body no-padding-bottom">
    <div class="tab-content">
      
      {{ guideForm.cities }}
  
    </div>
  </div>
</div>

</form>


<button type="submit" class="btn btn-success" form="editguide">Update guide</button>
{% endblock %}

templates/guides/guides.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<table class="table table-condensed">
  <h1>Guides</h1>
  <tr>
    <th>City</th>
    <th>Country</th>
    <th>Address</th>
    <th>Language</th>
    <th>
      {% url 'manage_guides:add_guide' as add %}
      <a href="{{ add }}">
        <button class="btn btn-success">
          <i class="fa fa-plus"></i>
        </button>
      </a>
    </th>
  </tr>
  {% for guide in guides %}
  <tr>
    <td>{{ guide.city }}</td>
    <td>{{ guide.country }}</td>
    <td>{{ guide.address }} </td>
    <td>{{ guide.language }}</td>
    <td>
      {% url 'manage_guides:edit_guide' guide.id as edit %}
      {% url 'manage_guides:delete_guide' guide.id as delete %}
        <a href="{{ edit }}">
          <button class="btn btn-primary">
            <i class="fa fa-pencil-square-o"></i>
          </button>
        </a>
        <a href="{{ delete }}">
          <button class="btn btn-danger">
            <i class="fa fa-trash-o"></i>
          </button>
        </a>
    </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}