registrations/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url(r'^$', views.sign_up, name='sign_up'),
    url(r'^login/$', auth_views.login, {'template_name': 'page-login.html'},
        name='login'),  # name login
    url(r'^logout/$', auth_views.logout, name='logout'),
]

tours/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.overview, name='overview'),
    url(r'^addtour/$', views.add_tour, name='add_tour'),
    url(r'^showstops/([0-9]+)$', views.show_stops, name='show_stops'),
    url(r'^edittour/([0-9]+)$', views.edit_tour, name='edit_tour'),
    url(r'^deletetour/([0-9]+)$', views.delete_tour, name='delete_tour'),
    url(r'^deletestop/([0-9]+)$', views.delete_stop, name='delete_stop'),
]

travel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^guides/', include('guides.urls', namespace='manage_guides')),
    url(r'^tours/', include('tours.urls', namespace='manage_tours')),
    url(r'^suppliers/', include('suppliers.urls', namespace='manage_suppliers')),
    url(r'^registrations/', include('registrations.urls', namespace='registrations')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
	<head>
    	<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="CleverAdmin - Bootstrap Admin Template">
		<meta name="author" content="Łukasz Holeczek">
		<meta name="keyword" content="CleverAdmin, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
	    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "ico/apple-touch-icon-144-precomposed.png" %}">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "ico/apple-touch-icon-114-precomposed.png" %}">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "ico/apple-touch-icon-72-precomposed.png" %}">
		<link rel="apple-touch-icon-precomposed" sizes="57x57" href="{% static "ico/apple-touch-icon-57-precomposed.png" %}">
		<link rel="shortcut icon" href="{% static "ico/favicon.png" %}">

	    <title>cleverAdmin - Bootstrap Admin Template</title>

	    <!-- Bootstrap core CSS -->
	    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

		<!-- page css files -->
		<link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
		<link href="{% static "css/jquery-ui.min.css" %}" rel="stylesheet">

	    <!-- Custom styles for this template -->
	    <link href="{% static "css/style.min.css" %}" rel="stylesheet">
		<link href="{% static "css/custom.css" %}" rel="stylesheet">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	</head>

<body>
		<!-- start: Header -->
	<div class="navbar" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">

				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar">a</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" data-toggle="modal" href="#myModal">{{City}}</a>
	    </div>
			<ul class="nav navbar-nav navbar-actions navbar-left">
				<li><a href="page-profile.html#" id="main-menu-toggle"><i class="fa fa-bars"></i></a></li>
			</ul>
	      <ul class="nav navbar-nav navbar-right">

					<li><a href="">{{ User }}</a></li>
					<li><a href="{% url 'registrations:logout' %}"><i class="fa fa-power-off"></i></a></li>

			</ul>

		</div>
	</div>
	<!-- end: Header -->

		<div class="container-fluid content">
		<div class="row">

			<!-- start: Main Menu -->
			<div class="sidebar col-md-2 col-sm-1 ">

				<div class="sidebar-collapse collapse">
					<div class="nav-sidebar title"><span>Main Menu</span></div>
					<ul class="nav nav-sidebar">

						<li><a href="index.html"><span class="hidden-sm text"> New booking</span></a></li>
						<li><a href="{% url 'manage_guides:overview' %}"><span class="hidden-sm text"> Guides</span></a></li>
						<li><a href="{% url 'manage_tours:overview' %}"><span class="hidden-sm text"> Tours</span></a></li>
						<li><a href="{% url 'manage_suppliers:overview' %}"><span class="hidden-sm text"> Suppliers</span></a></li>
						<li><a href="index.html"><span class="hidden-sm text"> Organisations</span></a></li>
						<li><a href="index.html"><span class="hidden-sm text"> Individuals</span></a></li>

					</ul>
				</div>
				<a href="page-profile.html#" id="main-menu-min" class="full visible-md visible-lg"><i class="fa fa-angle-double-left"></i></a>
			</div>

			<!-- end: Main Menu -->

			<!-- start: Content -->

			<div class="col-md-10 col-sm-11 main ">

		 {% block content %}
		 {% endblock %}

			</div>
			<!-- end: Content -->
		</div><!--/row-->


	</div><!--/container-->
	<!-- Modal -->
	<div id="myModal" class="modal fade" role="dialog">
	  <div class="modal-dialog">

	    <!-- Modal content-->
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title">Select city</h4>
	      </div>
	      <div class="modal-body">
	        {% for row in Cities %}
	        <p><a href="?id_city={{row.id}}">{{row}}</a></p>
	        {% endfor %}
	        <p><a href="?id_city=all">All cities</a></p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>

	  </div>
	</div>

	<div class="clearfix"></div>
	<script>
		$("#myModal").modal;
	</script>
	<footer>


	</footer>

	<!-- start: JavaScript-->
	<script src="{% static "js/jquery-migrate-1.2.1.min.js" %}"></script>
	<script src="{% static "js/bootstrap.min.js" %}"></script>


	<!-- page scripts -->
	<script src="{% static "js/jquery-ui.min.js" %}"></script>
	<script src="{% static "js/script.js" %}"></script>
	<!--[if lt IE 9]><script language="javascript" type="text/javascript" src="assets/js/excanvas.min.js"></script><![endif]-->
	<script src="{% static "js/Chart.min.js" %}"></script>
	<script src="{% static "js/jquery.easy-pie-chart.min.js" %}"></script>

	<!-- theme scripts -->
	<script src="{% static "js/custom.min.js" %}"></script>
	<script src="{% static "js/core.min.js" %}"></script>

	<!-- inline scripts related to this page -->


	<!-- end: JavaScript-->

</body>
</html>